version: '3.7'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.5.0
#    hostname: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888, zookeeper-2:2888:3888,zookeeper-3:2888:3888
    ports:
      - "2181:2181"
#      - "2888:2888"
#      - "3888:3888"

#  zookeeper-2:
#    image: confluentinc/cp-zookeeper:7.5.0
#    hostname: zookeeper-2
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SERVER_ID: 2
#      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888, zookeeper-2:2888:3888,zookeeper-3:2888:3888
#    ports:
#      - "2182:2181"
#      - "2889:2888"
#      - "3889:3888"
#
#  zookeeper-3:
#    image: confluentinc/cp-zookeeper:7.5.0
#    hostname: zookeeper-3
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SERVER_ID: 3
#      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888, zookeeper-2:2888:3888,zookeeper-3:2888:3888
#    ports:
#      - "2183:2181"
#      - "2890:2888"
#      - "3890:3888"


  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9093:9092"

  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9094:9092"